exclude = [
  'https://flakehub.com\.*',
  'https://github.com\.*',   # TODO: remove this when we figure out a way around GitHub's rate limits
  'https://developer.hashicorp.com/terraform\.*', # gets rate limited
  'file://*',
  'https://gnu.org/software/bash',
  'https://gcc.gnu.org',
  'https://guix.gnu.org',
  'https://wiki.nixos.org\.*'
]
